//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFID.Droid {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RFID.Droid.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string home_title {
            get {
                return ResourceManager.GetString("home_title", resourceCulture);
            }
        }
        
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        public static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
        }
        
        public static string read {
            get {
                return ResourceManager.GetString("read", resourceCulture);
            }
        }
        
        public static string exception {
            get {
                return ResourceManager.GetString("exception", resourceCulture);
            }
        }
        
        public static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
        
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        public static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        public static string inputserver {
            get {
                return ResourceManager.GetString("inputserver", resourceCulture);
            }
        }
        
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        public static string setsuccess {
            get {
                return ResourceManager.GetString("setsuccess", resourceCulture);
            }
        }
        
        public static string servererror {
            get {
                return ResourceManager.GetString("servererror", resourceCulture);
            }
        }
        
        public static string query {
            get {
                return ResourceManager.GetString("query", resourceCulture);
            }
        }
        
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        public static string mine {
            get {
                return ResourceManager.GetString("mine", resourceCulture);
            }
        }
        
        public static string uhfno {
            get {
                return ResourceManager.GetString("uhfno", resourceCulture);
            }
        }
        
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        public static string scanmode {
            get {
                return ResourceManager.GetString("scanmode", resourceCulture);
            }
        }
        
        public static string remember {
            get {
                return ResourceManager.GetString("remember", resourceCulture);
            }
        }
        
        public static string outline {
            get {
                return ResourceManager.GetString("outline", resourceCulture);
            }
        }
        
        public static string qrcodemode {
            get {
                return ResourceManager.GetString("qrcodemode", resourceCulture);
            }
        }
        
        public static string nfcmode {
            get {
                return ResourceManager.GetString("nfcmode", resourceCulture);
            }
        }
        
        public static string uhfmode {
            get {
                return ResourceManager.GetString("uhfmode", resourceCulture);
            }
        }
        
        public static string qrcode {
            get {
                return ResourceManager.GetString("qrcode", resourceCulture);
            }
        }
        
        public static string nfc {
            get {
                return ResourceManager.GetString("nfc", resourceCulture);
            }
        }
        
        public static string uhf {
            get {
                return ResourceManager.GetString("uhf", resourceCulture);
            }
        }
        
        public static string modeselect {
            get {
                return ResourceManager.GetString("modeselect", resourceCulture);
            }
        }
        
        public static string pwdchange {
            get {
                return ResourceManager.GetString("pwdchange", resourceCulture);
            }
        }
        
        public static string nfcread {
            get {
                return ResourceManager.GetString("nfcread", resourceCulture);
            }
        }
        
        public static string nonfc {
            get {
                return ResourceManager.GetString("nonfc", resourceCulture);
            }
        }
        
        public static string qrerror {
            get {
                return ResourceManager.GetString("qrerror", resourceCulture);
            }
        }
        
        public static string sacndetail {
            get {
                return ResourceManager.GetString("sacndetail", resourceCulture);
            }
        }
        
        public static string scan {
            get {
                return ResourceManager.GetString("scan", resourceCulture);
            }
        }
        
        public static string unknowntag {
            get {
                return ResourceManager.GetString("unknowntag", resourceCulture);
            }
        }
        
        public static string nfc_unable {
            get {
                return ResourceManager.GetString("nfc_unable", resourceCulture);
            }
        }
        
        public static string not_outline {
            get {
                return ResourceManager.GetString("not_outline", resourceCulture);
            }
        }
        
        public static string login_null {
            get {
                return ResourceManager.GetString("login_null", resourceCulture);
            }
        }
        
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        public static string car_title {
            get {
                return ResourceManager.GetString("car_title", resourceCulture);
            }
        }
        
        public static string car {
            get {
                return ResourceManager.GetString("car", resourceCulture);
            }
        }
        
        public static string curaddress {
            get {
                return ResourceManager.GetString("curaddress", resourceCulture);
            }
        }
        
        public static string locating {
            get {
                return ResourceManager.GetString("locating", resourceCulture);
            }
        }
        
        public static string checklock {
            get {
                return ResourceManager.GetString("checklock", resourceCulture);
            }
        }
        
        public static string lockend {
            get {
                return ResourceManager.GetString("lockend", resourceCulture);
            }
        }
        
        public static string carinfo {
            get {
                return ResourceManager.GetString("carinfo", resourceCulture);
            }
        }
        
        public static string starttime {
            get {
                return ResourceManager.GetString("starttime", resourceCulture);
            }
        }
        
        public static string lockplace {
            get {
                return ResourceManager.GetString("lockplace", resourceCulture);
            }
        }
        
        public static string isdelete {
            get {
                return ResourceManager.GetString("isdelete", resourceCulture);
            }
        }
        
        public static string deleteinfo {
            get {
                return ResourceManager.GetString("deleteinfo", resourceCulture);
            }
        }
        
        public static string acar {
            get {
                return ResourceManager.GetString("acar", resourceCulture);
            }
        }
        
        public static string pleaseselect {
            get {
                return ResourceManager.GetString("pleaseselect", resourceCulture);
            }
        }
        
        public static string takephoto {
            get {
                return ResourceManager.GetString("takephoto", resourceCulture);
            }
        }
        
        public static string album {
            get {
                return ResourceManager.GetString("album", resourceCulture);
            }
        }
        
        public static string nophoto {
            get {
                return ResourceManager.GetString("nophoto", resourceCulture);
            }
        }
        
        public static string noalbum {
            get {
                return ResourceManager.GetString("noalbum", resourceCulture);
            }
        }
        
        public static string driver {
            get {
                return ResourceManager.GetString("driver", resourceCulture);
            }
        }
        
        public static string place {
            get {
                return ResourceManager.GetString("place", resourceCulture);
            }
        }
        
        public static string qianfengno {
            get {
                return ResourceManager.GetString("qianfengno", resourceCulture);
            }
        }
        
        public static string qianfengphoto {
            get {
                return ResourceManager.GetString("qianfengphoto", resourceCulture);
            }
        }
        
        public static string carhint {
            get {
                return ResourceManager.GetString("carhint", resourceCulture);
            }
        }
        
        public static string driverhint {
            get {
                return ResourceManager.GetString("driverhint", resourceCulture);
            }
        }
        
        public static string qrcodehint {
            get {
                return ResourceManager.GetString("qrcodehint", resourceCulture);
            }
        }
        
        public static string placehint {
            get {
                return ResourceManager.GetString("placehint", resourceCulture);
            }
        }
        
        public static string arrival {
            get {
                return ResourceManager.GetString("arrival", resourceCulture);
            }
        }
        
        public static string arrivalhint {
            get {
                return ResourceManager.GetString("arrivalhint", resourceCulture);
            }
        }
        
        public static string shifeng {
            get {
                return ResourceManager.GetString("shifeng", resourceCulture);
            }
        }
        
        public static string newpwd {
            get {
                return ResourceManager.GetString("newpwd", resourceCulture);
            }
        }
        
        public static string oldpwd {
            get {
                return ResourceManager.GetString("oldpwd", resourceCulture);
            }
        }
        
        public static string repwd {
            get {
                return ResourceManager.GetString("repwd", resourceCulture);
            }
        }
        
        public static string changesuccess {
            get {
                return ResourceManager.GetString("changesuccess", resourceCulture);
            }
        }
        
        public static string uhfset {
            get {
                return ResourceManager.GetString("uhfset", resourceCulture);
            }
        }
        
        public static string powerset {
            get {
                return ResourceManager.GetString("powerset", resourceCulture);
            }
        }
        
        public static string power {
            get {
                return ResourceManager.GetString("power", resourceCulture);
            }
        }
        
        public static string carex {
            get {
                return ResourceManager.GetString("carex", resourceCulture);
            }
        }
        
        public static string checkphoto {
            get {
                return ResourceManager.GetString("checkphoto", resourceCulture);
            }
        }
        
        public static string endphoto {
            get {
                return ResourceManager.GetString("endphoto", resourceCulture);
            }
        }
        
        public static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        public static string delivery {
            get {
                return ResourceManager.GetString("delivery", resourceCulture);
            }
        }
        
        public static string deliveryphoto {
            get {
                return ResourceManager.GetString("deliveryphoto", resourceCulture);
            }
        }
        
        public static string exphoto {
            get {
                return ResourceManager.GetString("exphoto", resourceCulture);
            }
        }
        
        public static string explace {
            get {
                return ResourceManager.GetString("explace", resourceCulture);
            }
        }
        
        public static string exinfo {
            get {
                return ResourceManager.GetString("exinfo", resourceCulture);
            }
        }
        
        public static string explease {
            get {
                return ResourceManager.GetString("explease", resourceCulture);
            }
        }
        
        public static string exsubmit {
            get {
                return ResourceManager.GetString("exsubmit", resourceCulture);
            }
        }
        
        public static string shaixuan {
            get {
                return ResourceManager.GetString("shaixuan", resourceCulture);
            }
        }
        
        public static string please {
            get {
                return ResourceManager.GetString("please", resourceCulture);
            }
        }
    }
}
